#!/usr/bin/env python3
"""
Extract Calculator Code from Saved Task
"""

import json
import re
import sys
def extract_calculator_code(file: str):
    """Extract the calculator code from caclapp.json and save it"""
    
    # Load the saved task
    with open(file, 'r') as f:
        task_data = json.load(f)
    
    # Get the final code
    final_code = task_data["final_code"]
    
    # Extract Python code blocks
    python_blocks = re.findall(r'```python\n(.*?)\n```', final_code, re.DOTALL)
    
    if python_blocks:
        # Use the first complete calculator implementation (Block 1)
        calculator_code = python_blocks[0]
        
        # Add header comment
        header = """# Generated by AgentMesh - Calculator Application
# Original Task: create a calculator application
# This is a simple calculator with GUI using Tkinter

"""
        
        # Combine header and code
        full_code = header + calculator_code
        
        # Save to file
        with open(f'{file.split(".")[0]}.py', 'w') as f:
            f.write(full_code)
        
        print("✅ Calculator code extracted and saved to 'calculator_app.py'")
        print("📝 You can now run: python3 calculator_app.py")
        
        return True
    else:
        print("❌ No Python code blocks found in the saved task")
        return False

if __name__ == "__main__":
    args = sys.argv[1:]
    extract_calculator_code(args[0]) 